# Generated by Django 4.2.5 on 2023-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='lama', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.IntegerField(null=True),
        ),
    ]
