# Generated by Django 4.2.5 on 2023-09-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_alter_player_avatar_alter_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.deck'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_api.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_num',
            field=models.PositiveIntegerField(),
        ),
    ]
