# Generated by Django 4.2.5 on 2023-09-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0004_alter_game_deck_alter_player_game_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='game_api.player'),
        ),
    ]
