# Generated by Django 4.2.5 on 2023-09-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0005_rename_game_id_player_game_alter_game_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_api.game'),
        ),
    ]
