# Generated by Django 4.2.5 on 2023-09-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0010_playercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='members_num',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_api.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='association_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.IntegerField()),
                ('gameplay', models.IntegerField()),
                ('recomendation', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game_api.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game_api.round')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='game_api.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='game_api.round')),
            ],
        ),
    ]
