# Generated by Django 4.2.5 on 2023-09-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0011_alter_game_members_num_alter_player_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game_api.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='game_api.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('NR', 'Not Ready'), ('RD', 'Ready')], default='NR', max_length=2),
        ),
    ]
