# Generated by Django 4.2.5 on 2023-10-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0012_game_winner_alter_game_creator_alter_player_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='player',
        ),
        migrations.AddField(
            model_name='card',
            name='games',
            field=models.ManyToManyField(related_name='cards', to='game_api.game'),
        ),
        migrations.AddField(
            model_name='card',
            name='players',
            field=models.ManyToManyField(related_name='cards', to='game_api.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game_api.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_api.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='association_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GameCard',
        ),
        migrations.DeleteModel(
            name='PlayerCard',
        ),
    ]
