# Generated by Django 4.2.5 on 2023-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0013_remove_playercard_card_remove_playercard_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='game_api.game'),
        ),
        migrations.AlterField(
            model_name='card',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='game_api.player'),
        ),
    ]
