# Generated by Django 4.2.5 on 2023-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0014_alter_card_games_alter_card_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='cards', to='game_api.game'),
        ),
        migrations.AlterField(
            model_name='card',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='cards', to='game_api.player'),
        ),
    ]
