# Generated by Django 4.2.5 on 2023-10-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0015_alter_card_games_alter_card_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WT', 'Waiting'), ('PL', 'Playing'), ('FN', 'Finished')], default='WT', max_length=2),
        ),
    ]
